# Dev environment overrides
replicaCount: 1

resources:
  requests:
    memory: "32Mi"
    cpu: "50m"
  limits:
    memory: "64Mi"
    cpu: "100m"

ingress:
  className: "nginx-tietoevry"
  host: csa-demo-container-mj.dev.tietoevry.platform-engineer.cloud
  tls:
    enabled: true
    secretName: csa-demo-container-mj-dev-tls
